[kspenko@ccw02 examples]$ basf2 masterclass.py 
[INFO] Steering file: masterclass.py
[INFO] Starting event processing, random seed is set to 'd94f01797796e587e59b2785829c69cf7d329b71a6bd895ed542062ff0f9675a'
[FATAL] You have to set either the 'inputFileName' or the 'inputFileNames' parameter, or start basf2 with the '-i MyFile.root' option.  { module: RootInput function: virtual void Belle2::RootInputModule::initialize() }
[INFO] ===Error Summary================================================================
[FATAL] You have to set either the 'inputFileName' or the 'inputFileNames' parameter, or start basf2 with the '-i MyFile.root' option.  { module: RootInput }
[INFO] ================================================================================
[kspenko@ccw02 examples]$ b2env
Warning: Changing existing PYTHONPATH from /cvmfs/belle.cern.ch/el7/externals/v02-00-01/Linux_x86_64/common/root/lib:/gpfs/home/belle2/kspenko/basf2/lib/Linux_x86_64/opt:/cvmfs/belle.cern.ch/tools to /cvmfs/belle.cern.ch/tools
Belle II software tools set up at: /cvmfs/belle.cern.ch/tools
[kspenko@ccw02 examples]$ b2setup release-06-00-05
Environment setup for release: release-06-00-05
Central release directory    : /cvmfs/belle.cern.ch/el7/releases/release-06-00-05
Warning: The release release-06-00-05 is not supported any more. Please update to release-06-00-14
[kspenko@ccw02 examples]$ basf2 -i /group/belle2/dataprod/MC/MC15ri/charged/sub00/mdst_000111_prod00024816_task10020000110.root masterclass.py
[INFO] Steering file: masterclass.py
[INFO] Starting event processing, random seed is set to '534d82a349aef2cdbf6e8247a767f4f89257e7e91a56e4f47063d35e740838f5'
[INFO] Added file /group/belle2/dataprod/MC/MC15ri/charged/sub00/mdst_000111_prod00024816_task10020000110.root
[INFO] Conditions Database: found working server
        url = http://belle2db.sdcc.bnl.gov/b2s/rest/
[INFO] Conditions data: configured globaltags (highest priority first) are mc_production_MC15ri_a, release-06-00-07
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007ff385ffe659 in waitpid () from /lib64/libc.so.6
#1  0x00007ff385f7bf62 in do_system () from /lib64/libc.so.6
#2  0x00007ff385f7c311 in system () from /lib64/libc.so.6
#3  0x00007ff385d09eec in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x21e9570) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/core/unix/src/TUnixSystem.cxx:2120
#4  TUnixSystem::StackTrace (this=0x21e9570) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/core/unix/src/TUnixSystem.cxx:2411
#5  0x00007ff383017cd2 in (anonymous namespace)::do_trace (sig=1) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:182
#6  (anonymous namespace)::TExceptionHandlerImp::HandleException (this=<optimized out>, sig=1) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:195
#7  0x00007ff385d07371 in TUnixSystem::DispatchSignals (this=0x21e9570, sig=kSigSegmentationViolation) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/core/unix/src/TUnixSystem.cxx:3644
#8  <signal handler called>
#9  0x00007ff36be373b6 in TObject::TObject (this=0x0) at /home/b2soft/externals/v01-10-02/include/root/TObject.h:241
#10 BParticle::BParticle (this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>, this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>) at masterclass/dataobjects/src/BParticle.cc:13
#11 0x00007ff36be374c2 in BEvent::AddTrack (this=<optimized out>, px=-0.162041083, py=0.180440441, pz=-0.351187855, e=0.449031025, charge=-1, pid=PION) at masterclass/dataobjects/src/BEvent.cc:37
#12 0x00007ff36bf02dff in Belle2::MasterClassModule::event (this=0x57a54b0) at /home/b2soft/externals/v01-10-02/include/root/TVector3.h:213
#13 0x00007ff386c3bd8d in Belle2::EventProcessor::callEvent (this=0x7ffc8abc0700, module=0x57a54b0) at framework/core/src/EventProcessor.cc:223
#14 0x00007ff386c3d06c in Belle2::EventProcessor::processEvent (this=0x7ffc8abc0700, moduleIter=..., skipMasterModule=true) at framework/core/src/EventProcessor.cc:324
#15 0x00007ff386c3dedb in Belle2::EventProcessor::processCore (this=0x7ffc8abc0700, startPath=..., modulePathList=..., maxEvent=0, isInputProcess=true) at framework/core/src/EventProcessor.cc:411
#16 0x00007ff386c3e931 in Belle2::EventProcessor::process (this=this
entry=0x7ffc8abc0700, startPath=..., maxEvent=maxEvent
entry=0) at framework/core/src/EventProcessor.cc:165
#17 0x00007ff36bf79b38 in Belle2::Framework::process (startPath=..., maxEvent=0) at framework/pybasf2/src/Framework.cc:134
#18 0x00007ff36bf7a47f in process_overloads::non_void_return_type::gen<boost::mpl::vector3<void, std::shared_ptr<Belle2::Path>, long> >::func_0 (arg0=...) at framework/pybasf2/src/Framework.cc:275
#19 0x00007ff36bf761bc in boost::python::detail::invoke<int, void (*)(std::shared_ptr<Belle2::Path>), boost::python::arg_from_python<std::shared_ptr<Belle2::Path> > > (f=<optimized out>, f=<optimized out>, ac0=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/invoke.hpp:79
#20 boost::python::detail::caller_arity<1u>::impl<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > >::operator() (args_=<optimized out>, this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/caller.hpp:233
#21 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > > >::operator() (this=<optimized out>, args=<optimized out>, kw=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/object/py_function.hpp:38
#22 0x00007ff3870267ab in boost::python::objects::function::call(_object*, _object*) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#23 0x00007ff387026a28 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#24 0x00007ff38702b7cb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#25 0x00007ff36bf6fd48 in boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>::operator() (this=<optimized out>, translate=0x7ff36bf6fa80 <(anonymous namespace)::moduleNotCreatedTranslator(Belle2::ModuleManager::ModuleNotCreatedError const&)>, f=..., handler=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/translate_exception.hpp:46
#26 boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> >::operator()<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (a=<synthetic pointer>..., f=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:366
#27 boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (a2=..., a1=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:1296
#28 boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...) at /home/b2soft/externals/v01-10-02/include/boost/function/function_template.hpp:137
#29 0x00007ff38702b70f in boost::python::handle_exception_impl(boost::function0<void>) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#30 0x00007ff387024302 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#31 0x00007ff38550e1f7 in _PyObject_MakeTpCall (callable=0x38f9040, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:159
#32 0x00007ff3854e1de3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x38f9040) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:125
#33 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:115
#34 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0cc8, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#35 0x00007ff3854e895d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3469
#36 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=globals
entry=0x7ff36c002500, locals=locals
entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=0x7ff36c46cb68, kwcount=0, kwstep=1, defs=0x7ff36bffee08, defcount=1, kwdefs=0x0, closure=0x0, name=0x7ff36c3aa7b0, qualname=0x7ff36c3aa7b0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#37 0x00007ff38550dfb1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:436
#38 0x00007ff3854e1d5d in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:127
#39 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0f80, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#40 0x00007ff3854e4c63 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3500
#41 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kwnames=kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#42 0x00007ff3855ea4fe in PyEval_EvalCodeEx (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4327
#43 0x00007ff3855ea52b in PyEval_EvalCode (co=co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:718
#44 0x00007ff3856292fc in run_eval_code_obj (locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, co=0x7ff36c45d0e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1165
#45 run_mod (mod=mod
entry=0x38f4570, filename=filename
entry=0x7ff36c0b7cb0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, flags=flags
entry=0x0, arena=arena
entry=0x7ff36c054850) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1187
#46 0x00007ff38562b1d0 in pyrun_file (flags=0x0, closeit=0, locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, start=<optimized out>, filename=0x7ff36c0b7cb0, fp=0x38f35e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1084
#47 PyRun_FileExFlags (fp=0x38f35e0, filename=<optimized out>, start=<optimized out>, globals=0x7ff36c5d7840, locals=0x7ff36c5d7840, closeit=0, flags=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1104
#48 0x00007ff38702f3dd in boost::python::exec_file(char const*, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#49 0x00007ff38702f574 in boost::python::exec_file(boost::python::str, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#50 0x000000000040d795 in (anonymous namespace)::executePythonFile (pythonFile=...) at framework/tools/basf2.cc:80
#51 main (argc=<optimized out>, argv=0x7ffc8abc1f18) at framework/tools/basf2.cc:448
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#9  0x00007ff36be373b6 in TObject::TObject (this=0x0) at /home/b2soft/externals/v01-10-02/include/root/TObject.h:241
#10 BParticle::BParticle (this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>, this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>) at masterclass/dataobjects/src/BParticle.cc:13
#11 0x00007ff36be374c2 in BEvent::AddTrack (this=<optimized out>, px=-0.162041083, py=0.180440441, pz=-0.351187855, e=0.449031025, charge=-1, pid=PION) at masterclass/dataobjects/src/BEvent.cc:37
#12 0x00007ff36bf02dff in Belle2::MasterClassModule::event (this=0x57a54b0) at /home/b2soft/externals/v01-10-02/include/root/TVector3.h:213
#13 0x00007ff386c3bd8d in Belle2::EventProcessor::callEvent (this=0x7ffc8abc0700, module=0x57a54b0) at framework/core/src/EventProcessor.cc:223
#14 0x00007ff386c3d06c in Belle2::EventProcessor::processEvent (this=0x7ffc8abc0700, moduleIter=..., skipMasterModule=true) at framework/core/src/EventProcessor.cc:324
#15 0x00007ff386c3dedb in Belle2::EventProcessor::processCore (this=0x7ffc8abc0700, startPath=..., modulePathList=..., maxEvent=0, isInputProcess=true) at framework/core/src/EventProcessor.cc:411
#16 0x00007ff386c3e931 in Belle2::EventProcessor::process (this=this
entry=0x7ffc8abc0700, startPath=..., maxEvent=maxEvent
entry=0) at framework/core/src/EventProcessor.cc:165
#17 0x00007ff36bf79b38 in Belle2::Framework::process (startPath=..., maxEvent=0) at framework/pybasf2/src/Framework.cc:134
#18 0x00007ff36bf7a47f in process_overloads::non_void_return_type::gen<boost::mpl::vector3<void, std::shared_ptr<Belle2::Path>, long> >::func_0 (arg0=...) at framework/pybasf2/src/Framework.cc:275
#19 0x00007ff36bf761bc in boost::python::detail::invoke<int, void (*)(std::shared_ptr<Belle2::Path>), boost::python::arg_from_python<std::shared_ptr<Belle2::Path> > > (f=<optimized out>, f=<optimized out>, ac0=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/invoke.hpp:79
#20 boost::python::detail::caller_arity<1u>::impl<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > >::operator() (args_=<optimized out>, this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/caller.hpp:233
#21 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > > >::operator() (this=<optimized out>, args=<optimized out>, kw=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/object/py_function.hpp:38
#22 0x00007ff3870267ab in boost::python::objects::function::call(_object*, _object*) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#23 0x00007ff387026a28 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#24 0x00007ff38702b7cb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#25 0x00007ff36bf6fd48 in boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>::operator() (this=<optimized out>, translate=0x7ff36bf6fa80 <(anonymous namespace)::moduleNotCreatedTranslator(Belle2::ModuleManager::ModuleNotCreatedError const&)>, f=..., handler=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/translate_exception.hpp:46
#26 boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> >::operator()<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (a=<synthetic pointer>..., f=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:366
#27 boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (a2=..., a1=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:1296
#28 boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...) at /home/b2soft/externals/v01-10-02/include/boost/function/function_template.hpp:137
#29 0x00007ff38702b70f in boost::python::handle_exception_impl(boost::function0<void>) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#30 0x00007ff387024302 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#31 0x00007ff38550e1f7 in _PyObject_MakeTpCall (callable=0x38f9040, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:159
#32 0x00007ff3854e1de3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x38f9040) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:125
#33 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:115
#34 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0cc8, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#35 0x00007ff3854e895d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3469
#36 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=globals
entry=0x7ff36c002500, locals=locals
entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=0x7ff36c46cb68, kwcount=0, kwstep=1, defs=0x7ff36bffee08, defcount=1, kwdefs=0x0, closure=0x0, name=0x7ff36c3aa7b0, qualname=0x7ff36c3aa7b0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#37 0x00007ff38550dfb1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:436
#38 0x00007ff3854e1d5d in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:127
#39 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0f80, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#40 0x00007ff3854e4c63 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3500
#41 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kwnames=kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#42 0x00007ff3855ea4fe in PyEval_EvalCodeEx (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4327
#43 0x00007ff3855ea52b in PyEval_EvalCode (co=co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:718
#44 0x00007ff3856292fc in run_eval_code_obj (locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, co=0x7ff36c45d0e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1165
#45 run_mod (mod=mod
entry=0x38f4570, filename=filename
entry=0x7ff36c0b7cb0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, flags=flags
entry=0x0, arena=arena
entry=0x7ff36c054850) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1187
#46 0x00007ff38562b1d0 in pyrun_file (flags=0x0, closeit=0, locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, start=<optimized out>, filename=0x7ff36c0b7cb0, fp=0x38f35e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1084
#47 PyRun_FileExFlags (fp=0x38f35e0, filename=<optimized out>, start=<optimized out>, globals=0x7ff36c5d7840, locals=0x7ff36c5d7840, closeit=0, flags=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1104
#48 0x00007ff38702f3dd in boost::python::exec_file(char const*, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#49 0x00007ff38702f574 in boost::python::exec_file(boost::python::str, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#50 0x000000000040d795 in (anonymous namespace)::executePythonFile (pythonFile=...) at framework/tools/basf2.cc:80
#51 main (argc=<optimized out>, argv=0x7ffc8abc1f18) at framework/tools/basf2.cc:448
===========================================================


 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007ff385ffe659 in waitpid () from /lib64/libc.so.6
#1  0x00007ff385f7bf62 in do_system () from /lib64/libc.so.6
#2  0x00007ff385f7c311 in system () from /lib64/libc.so.6
#3  0x00007ff385d09eec in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x21e9570) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/core/unix/src/TUnixSystem.cxx:2120
#4  TUnixSystem::StackTrace (this=0x21e9570) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/core/unix/src/TUnixSystem.cxx:2411
#5  0x00007ff383017b5a in (anonymous namespace)::do_trace (sig=1) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:182
#6  (anonymous namespace)::TExceptionHandlerImp::HandleException (this=<optimized out>, sig=1) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx:201
#7  0x00007ff385d07371 in TUnixSystem::DispatchSignals (this=0x21e9570, sig=kSigSegmentationViolation) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/root/core/unix/src/TUnixSystem.cxx:3644
#8  <signal handler called>
#9  0x00007ff36be373b6 in TObject::TObject (this=0x0) at /home/b2soft/externals/v01-10-02/include/root/TObject.h:241
#10 BParticle::BParticle (this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>, this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>) at masterclass/dataobjects/src/BParticle.cc:13
#11 0x00007ff36be374c2 in BEvent::AddTrack (this=<optimized out>, px=-0.162041083, py=0.180440441, pz=-0.351187855, e=0.449031025, charge=-1, pid=PION) at masterclass/dataobjects/src/BEvent.cc:37
#12 0x00007ff36bf02dff in Belle2::MasterClassModule::event (this=0x57a54b0) at /home/b2soft/externals/v01-10-02/include/root/TVector3.h:213
#13 0x00007ff386c3bd8d in Belle2::EventProcessor::callEvent (this=0x7ffc8abc0700, module=0x57a54b0) at framework/core/src/EventProcessor.cc:223
#14 0x00007ff386c3d06c in Belle2::EventProcessor::processEvent (this=0x7ffc8abc0700, moduleIter=..., skipMasterModule=true) at framework/core/src/EventProcessor.cc:324
#15 0x00007ff386c3dedb in Belle2::EventProcessor::processCore (this=0x7ffc8abc0700, startPath=..., modulePathList=..., maxEvent=0, isInputProcess=true) at framework/core/src/EventProcessor.cc:411
#16 0x00007ff386c3e931 in Belle2::EventProcessor::process (this=this
entry=0x7ffc8abc0700, startPath=..., maxEvent=maxEvent
entry=0) at framework/core/src/EventProcessor.cc:165
#17 0x00007ff36bf79b38 in Belle2::Framework::process (startPath=..., maxEvent=0) at framework/pybasf2/src/Framework.cc:134
#18 0x00007ff36bf7a47f in process_overloads::non_void_return_type::gen<boost::mpl::vector3<void, std::shared_ptr<Belle2::Path>, long> >::func_0 (arg0=...) at framework/pybasf2/src/Framework.cc:275
#19 0x00007ff36bf761bc in boost::python::detail::invoke<int, void (*)(std::shared_ptr<Belle2::Path>), boost::python::arg_from_python<std::shared_ptr<Belle2::Path> > > (f=<optimized out>, f=<optimized out>, ac0=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/invoke.hpp:79
#20 boost::python::detail::caller_arity<1u>::impl<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > >::operator() (args_=<optimized out>, this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/caller.hpp:233
#21 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > > >::operator() (this=<optimized out>, args=<optimized out>, kw=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/object/py_function.hpp:38
#22 0x00007ff3870267ab in boost::python::objects::function::call(_object*, _object*) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#23 0x00007ff387026a28 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#24 0x00007ff38702b7cb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#25 0x00007ff36bf6fd48 in boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>::operator() (this=<optimized out>, translate=0x7ff36bf6fa80 <(anonymous namespace)::moduleNotCreatedTranslator(Belle2::ModuleManager::ModuleNotCreatedError const&)>, f=..., handler=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/translate_exception.hpp:46
#26 boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> >::operator()<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (a=<synthetic pointer>..., f=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:366
#27 boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (a2=..., a1=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:1296
#28 boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...) at /home/b2soft/externals/v01-10-02/include/boost/function/function_template.hpp:137
#29 0x00007ff38702b70f in boost::python::handle_exception_impl(boost::function0<void>) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#30 0x00007ff387024302 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#31 0x00007ff38550e1f7 in _PyObject_MakeTpCall (callable=0x38f9040, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:159
#32 0x00007ff3854e1de3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x38f9040) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:125
#33 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:115
#34 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0cc8, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#35 0x00007ff3854e895d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3469
#36 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=globals
entry=0x7ff36c002500, locals=locals
entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=0x7ff36c46cb68, kwcount=0, kwstep=1, defs=0x7ff36bffee08, defcount=1, kwdefs=0x0, closure=0x0, name=0x7ff36c3aa7b0, qualname=0x7ff36c3aa7b0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#37 0x00007ff38550dfb1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:436
#38 0x00007ff3854e1d5d in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:127
#39 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0f80, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#40 0x00007ff3854e4c63 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3500
#41 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kwnames=kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#42 0x00007ff3855ea4fe in PyEval_EvalCodeEx (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4327
#43 0x00007ff3855ea52b in PyEval_EvalCode (co=co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:718
#44 0x00007ff3856292fc in run_eval_code_obj (locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, co=0x7ff36c45d0e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1165
#45 run_mod (mod=mod
entry=0x38f4570, filename=filename
entry=0x7ff36c0b7cb0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, flags=flags
entry=0x0, arena=arena
entry=0x7ff36c054850) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1187
#46 0x00007ff38562b1d0 in pyrun_file (flags=0x0, closeit=0, locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, start=<optimized out>, filename=0x7ff36c0b7cb0, fp=0x38f35e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1084
#47 PyRun_FileExFlags (fp=0x38f35e0, filename=<optimized out>, start=<optimized out>, globals=0x7ff36c5d7840, locals=0x7ff36c5d7840, closeit=0, flags=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1104
#48 0x00007ff38702f3dd in boost::python::exec_file(char const*, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#49 0x00007ff38702f574 in boost::python::exec_file(boost::python::str, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#50 0x000000000040d795 in (anonymous namespace)::executePythonFile (pythonFile=...) at framework/tools/basf2.cc:80
#51 main (argc=<optimized out>, argv=0x7ffc8abc1f18) at framework/tools/basf2.cc:448
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#9  0x00007ff36be373b6 in TObject::TObject (this=0x0) at /home/b2soft/externals/v01-10-02/include/root/TObject.h:241
#10 BParticle::BParticle (this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>, this=<optimized out>, px=<optimized out>, py=<optimized out>, pz=<optimized out>, e=<optimized out>, charge=<optimized out>, pid=<optimized out>) at masterclass/dataobjects/src/BParticle.cc:13
#11 0x00007ff36be374c2 in BEvent::AddTrack (this=<optimized out>, px=-0.162041083, py=0.180440441, pz=-0.351187855, e=0.449031025, charge=-1, pid=PION) at masterclass/dataobjects/src/BEvent.cc:37
#12 0x00007ff36bf02dff in Belle2::MasterClassModule::event (this=0x57a54b0) at /home/b2soft/externals/v01-10-02/include/root/TVector3.h:213
#13 0x00007ff386c3bd8d in Belle2::EventProcessor::callEvent (this=0x7ffc8abc0700, module=0x57a54b0) at framework/core/src/EventProcessor.cc:223
#14 0x00007ff386c3d06c in Belle2::EventProcessor::processEvent (this=0x7ffc8abc0700, moduleIter=..., skipMasterModule=true) at framework/core/src/EventProcessor.cc:324
#15 0x00007ff386c3dedb in Belle2::EventProcessor::processCore (this=0x7ffc8abc0700, startPath=..., modulePathList=..., maxEvent=0, isInputProcess=true) at framework/core/src/EventProcessor.cc:411
#16 0x00007ff386c3e931 in Belle2::EventProcessor::process (this=this
entry=0x7ffc8abc0700, startPath=..., maxEvent=maxEvent
entry=0) at framework/core/src/EventProcessor.cc:165
#17 0x00007ff36bf79b38 in Belle2::Framework::process (startPath=..., maxEvent=0) at framework/pybasf2/src/Framework.cc:134
#18 0x00007ff36bf7a47f in process_overloads::non_void_return_type::gen<boost::mpl::vector3<void, std::shared_ptr<Belle2::Path>, long> >::func_0 (arg0=...) at framework/pybasf2/src/Framework.cc:275
#19 0x00007ff36bf761bc in boost::python::detail::invoke<int, void (*)(std::shared_ptr<Belle2::Path>), boost::python::arg_from_python<std::shared_ptr<Belle2::Path> > > (f=<optimized out>, f=<optimized out>, ac0=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/invoke.hpp:79
#20 boost::python::detail::caller_arity<1u>::impl<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > >::operator() (args_=<optimized out>, this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/caller.hpp:233
#21 boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(std::shared_ptr<Belle2::Path>), boost::python::default_call_policies, boost::mpl::vector2<void, std::shared_ptr<Belle2::Path> > > >::operator() (this=<optimized out>, args=<optimized out>, kw=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/python/object/py_function.hpp:38
#22 0x00007ff3870267ab in boost::python::objects::function::call(_object*, _object*) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#23 0x00007ff387026a28 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#24 0x00007ff38702b7cb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#25 0x00007ff36bf6fd48 in boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>::operator() (this=<optimized out>, translate=0x7ff36bf6fa80 <(anonymous namespace)::moduleNotCreatedTranslator(Belle2::ModuleManager::ModuleNotCreatedError const&)>, f=..., handler=...) at /home/b2soft/externals/v01-10-02/include/boost/python/detail/translate_exception.hpp:46
#26 boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> >::operator()<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (a=<synthetic pointer>..., f=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:366
#27 boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (a2=..., a1=..., this=<optimized out>) at /home/b2soft/externals/v01-10-02/include/boost/bind/bind.hpp:1296
#28 boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<Belle2::ModuleManager::ModuleNotCreatedError, void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(Belle2::ModuleManager::ModuleNotCreatedError const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...) at /home/b2soft/externals/v01-10-02/include/boost/function/function_template.hpp:137
#29 0x00007ff38702b70f in boost::python::handle_exception_impl(boost::function0<void>) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#30 0x00007ff387024302 in ?? () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#31 0x00007ff38550e1f7 in _PyObject_MakeTpCall (callable=0x38f9040, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:159
#32 0x00007ff3854e1de3 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x38f9040) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:125
#33 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:115
#34 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0cc8, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#35 0x00007ff3854e895d in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3469
#36 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=globals
entry=0x7ff36c002500, locals=locals
entry=0x0, args=<optimized out>, argcount=1, kwnames=0x0, kwargs=0x7ff36c46cb68, kwcount=0, kwstep=1, defs=0x7ff36bffee08, defcount=1, kwdefs=0x0, closure=0x0, name=0x7ff36c3aa7b0, qualname=0x7ff36c3aa7b0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#37 0x00007ff38550dfb1 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Objects/call.c:436
#38 0x00007ff3854e1d5d in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Include/cpython/abstract.h:127
#39 call_function (tstate=tstate
entry=0x3ffab80, pp_stack=pp_stack
entry=0x7ffc8abc0f80, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4963
#40 0x00007ff3854e4c63 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:3500
#41 0x00007ff3855ea15f in _PyEval_EvalCodeWithName (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kwnames=kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4298
#42 0x00007ff3855ea4fe in PyEval_EvalCodeEx (_co=_co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:4327
#43 0x00007ff3855ea52b in PyEval_EvalCode (co=co
entry=0x7ff36c45d0e0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/ceval.c:718
#44 0x00007ff3856292fc in run_eval_code_obj (locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, co=0x7ff36c45d0e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1165
#45 run_mod (mod=mod
entry=0x38f4570, filename=filename
entry=0x7ff36c0b7cb0, globals=globals
entry=0x7ff36c5d7840, locals=locals
entry=0x7ff36c5d7840, flags=flags
entry=0x0, arena=arena
entry=0x7ff36c054850) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1187
#46 0x00007ff38562b1d0 in pyrun_file (flags=0x0, closeit=0, locals=0x7ff36c5d7840, globals=0x7ff36c5d7840, start=<optimized out>, filename=0x7ff36c0b7cb0, fp=0x38f35e0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1084
#47 PyRun_FileExFlags (fp=0x38f35e0, filename=<optimized out>, start=<optimized out>, globals=0x7ff36c5d7840, locals=0x7ff36c5d7840, closeit=0, flags=0x0) at /cvmfs/belle.cern.ch/el7/externals/v01-10-02/src/python/Python/pythonrun.c:1104
#48 0x00007ff38702f3dd in boost::python::exec_file(char const*, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#49 0x00007ff38702f574 in boost::python::exec_file(boost::python::str, boost::python::api::object, boost::python::api::object) () from /cvmfs/belle.cern.ch/el7/externals/v01-10-02/Linux_x86_64/common/lib64/libboost_python38.so.1.75.0
#50 0x000000000040d795 in (anonymous namespace)::executePythonFile (pythonFile=...) at framework/tools/basf2.cc:80
#51 main (argc=<optimized out>, argv=0x7ffc8abc1f18) at framework/tools/basf2.cc:448
===========================================================
